### ISSUE TITLE
Add docs site

### ISSUE THREAD

**Issue by techpeace** [voxable/cli#7]
## Tasks
- [x] Create a Vuepress-powered docs site
- [x] Set up in Netlify
- [x] Configure docs.voxable.io domain
- [x] Enable discussions and link from docs

**Comment by techpeace** [comment]
See #11
